# Generated by Django 4.2.8 on 2025-05-03 15:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nv', models.CharField(max_length=100)),
                ('anh_ca_nhan', models.ImageField(upload_to='media/nhanvien/')),
                ('gioi_tinh', models.CharField(choices=[('2', 'Nam'), ('1', 'Nữ')], max_length=10)),
                ('ngay_sinh', models.DateField(null=True)),
                ('vi_tri_cong_viec', models.CharField(max_length=30)),
                ('to_phong_ban', models.CharField(choices=[('Lớp mầm', 'Lớp mầm'), ('Lớp chồi', 'Lớp chồi'), ('Lớp lá', 'Lớp lá'), ('Văn phòng', 'Văn phòng'), ('Y tế - Hậu cần', 'Y tế - Hậu cần')], max_length=50)),
                ('trinh_do_hoc_van', models.CharField(choices=[('Dưới trung cấp', 'Dưới trung cấp'), ('Trung cấp', 'Trung cấp'), ('Cao đẳng', 'Cao đẳng'), ('Đại học', 'Đại học'), ('Thạc sĩ', 'Thạc sĩ')], max_length=50)),
                ('chuyen_nganh', models.CharField(max_length=100, null=True)),
                ('noi_dao_tao', models.CharField(max_length=100)),
                ('nam_tn', models.IntegerField(null=True)),
                ('ngay_cap', models.DateField(null=True)),
                ('noi_cap', models.CharField(max_length=100)),
                ('dia_chi_tam_tru', models.TextField(null=True)),
                ('chuc_vu', models.CharField(max_length=150, null=True)),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Số điện thoại phải có đúng 10 chữ số.')])),
                ('email', models.EmailField(max_length=20, null=True, unique=True)),
                ('so_cccd', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Số CCCD phải có đúng 12 chữ số.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien_ho_so', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhuCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phu_cap', models.CharField(max_length=100)),
                ('gia_tri', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhuCapNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoSo.nhanvien')),
                ('phu_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoSo.phucap')),
            ],
        ),
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hop_dong', models.CharField(max_length=50)),
                ('thoi_han_hop_dong', models.IntegerField(verbose_name='Thời hạn hợp đồng')),
                ('loai_hop_dong', models.CharField(choices=[('Hợp đồng thử việc', 'Hợp đồng thử việc'), ('Hợp đồng có thời hạn', 'Hợp đồng có thời hạn')], default='Hợp đồng thử việc', max_length=100)),
                ('luong', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_ky', models.DateField()),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField()),
                ('trang_thai_hop_dong', models.CharField(choices=[('Đang hiệu lực', 'Đang hiệu lực'), ('Sắp hết hạn', 'Sắp hết hạn'), ('Đã chấm dứt', 'Đã chấm dứt')], max_length=50)),
                ('to_phong_ban', models.CharField(choices=[('Lớp mầm', 'Lớp mầm'), ('Lớp chồi', 'Lớp chồi'), ('Lớp lá', 'Lớp lá'), ('Văn phòng', 'Văn phòng'), ('Y tế - Hậu cần', 'Y tế - Hậu cần')], max_length=50)),
                ('vi_tri_lam_viec', models.CharField(choices=[('Giáo viên', 'Giáo viên'), ('Nhân viên văn phòng', 'Nhân viên văn phòng'), ('Quản lý', 'Quản lý')], max_length=50)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoSo.nhanvien')),
            ],
        ),
    ]
