# Generated by Django 4.2.8 on 2025-04-04 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nv', models.CharField(max_length=50)),
                ('anh_ca_nhan', models.CharField(blank=True, max_length=255, null=True)),
                ('so_cccd', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Số CCCD phải có đúng 12 chữ số.')])),
                ('ngay_sinh', models.DateField()),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Số điện thoại phải có đúng 10 chữ số.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('trinh_do_hoc_van', models.CharField(max_length=50)),
                ('kinh_nghiem_lam_viec', models.PositiveIntegerField(default=0)),
                ('vi_tri_cong_viec', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_hop_dong', models.CharField(max_length=100)),
                ('thoi_han_hop_dong', models.CharField(max_length=20)),
                ('ngay_vao_lam', models.DateField()),
                ('muc_luong', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('trang_thai_hop_dong', models.CharField(max_length=100)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HoSo.nhanvien')),
            ],
        ),
    ]
