# Generated by Django 4.2.8 on 2025-05-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoSo', '0002_alter_nhanvien_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phucapnhanvien',
            name='nhan_vien',
        ),
        migrations.RemoveField(
            model_name='phucapnhanvien',
            name='phu_cap',
        ),
        migrations.DeleteModel(
            name='HopDongLaoDong',
        ),
        migrations.DeleteModel(
            name='NhanVien',
        ),
        migrations.DeleteModel(
            name='PhuCap',
        ),
        migrations.DeleteModel(
            name='PhuCapNhanVien',
        ),
    ]
