# Generated by Django 4.2.19 on 2025-05-17 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nv', models.CharField(max_length=100)),
                ('anh_ca_nhan', models.ImageField(blank=True, null=True, upload_to='nhanvien/')),
                ('gioi_tinh', models.CharField(choices=[('2', 'Nam'), ('1', 'Nữ')], default='1', max_length=10)),
                ('ngay_sinh', models.DateField(null=True)),
                ('vi_tri_cong_viec', models.CharField(blank=True, max_length=100, null=True)),
                ('to_phong_ban', models.CharField(choices=[('Lớp mầm', 'Lớp mầm'), ('Lớp chồi', 'Lớp chồi'), ('Lớp lá', 'Lớp lá'), ('Văn phòng', 'Văn phòng'), ('Y tế - Hậu cần', 'Y tế - Hậu cần')], max_length=50)),
                ('trinh_do_hoc_van', models.CharField(choices=[('Dưới trung cấp', 'Dưới trung cấp'), ('Trung cấp', 'Trung cấp'), ('Cao đẳng', 'Cao đẳng'), ('Đại học', 'Đại học'), ('Thạc sĩ', 'Thạc sĩ')], max_length=50)),
                ('chuyen_nganh', models.CharField(max_length=100, null=True)),
                ('noi_dao_tao', models.CharField(max_length=100)),
                ('nam_tn', models.IntegerField(null=True)),
                ('ngay_cap', models.DateField(null=True)),
                ('noi_cap', models.CharField(max_length=100)),
                ('dia_chi_tam_tru', models.TextField(null=True)),
                ('chuc_vu', models.CharField(max_length=150, null=True)),
                ('so_dien_thoai', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('so_cccd', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'HOME_nhanvien',
            },
        ),
        migrations.CreateModel(
            name='PhuCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phu_cap', models.CharField(max_length=100)),
                ('gia_tri', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhuCapNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.nhanvien')),
                ('phu_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.phucap')),
            ],
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='phu_caps',
            field=models.ManyToManyField(blank=True, through='HOME.PhuCapNhanVien', to='HOME.phucap'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien_home', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NghiPhep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_nghi', models.CharField(max_length=100)),
                ('ngay_bat_dau', models.DateField(null=True)),
                ('ngay_ket_thuc', models.DateField(null=True)),
                ('ly_do', models.TextField()),
                ('trang_thai_don', models.CharField(default='Đang chờ duyệt', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao_don', models.DateTimeField(null=True)),
                ('ngay_chinh_sua', models.DateTimeField(null=True)),
                ('ngay_duyet', models.DateField(blank=True, null=True)),
                ('nguoi_duyet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_duyet_don', to='HOME.nhanvien')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_tao_don', to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='KyLuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField(null=True)),
                ('ngay_ra_quyet_dinh', models.DateField(null=True)),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True)),
                ('muc_do', models.CharField(choices=[('KY_LUAT_3_THANG', 'Kỷ luật 3 tháng'), ('KY_LUAT_6_THANG', 'Kỷ luật 6 tháng'), ('PHAT_TIEN', 'Phạt tiền')], max_length=20)),
                ('so_tien_phat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ly_do', models.TextField(null=True)),
                ('trang_thai', models.CharField(choices=[('DANG_CHO_DUYET', 'Đang chờ duyệt'), ('DA_DUYET', 'Đã duyệt')], default='DANG_CHO_DUYET', max_length=20)),
                ('minh_chung_file', models.FileField(blank=True, null=True, upload_to='minh_chung_ky_luat/')),
                ('minh_chung_url', models.URLField(blank=True, null=True)),
                ('nguoi_duyet_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ky_luat_duyet', to='HOME.nhanvien')),
                ('nguoi_tao_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ky_luat_tao', to='HOME.nhanvien')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ky_luat_nhan_vien', to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='KhenThuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('gia_tri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('DANG_CHO_DUYET', 'Đang chờ duyệt'), ('DA_DUYET', 'Đã duyệt')], default='DANG_CHO_DUYET', max_length=20)),
                ('minh_chung_file', models.FileField(blank=True, null=True, upload_to='minh_chung_khen_thuong/')),
                ('minh_chung_url', models.URLField(blank=True, null=True)),
                ('nguoi_tao_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khen_thuong_tao', to='HOME.nhanvien')),
                ('nguoi_xac_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khen_thuong_xac_nhan', to='HOME.nhanvien')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khen_thuong_nhan_vien', to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hop_dong', models.CharField(max_length=50)),
                ('thoi_han_hop_dong', models.IntegerField(verbose_name='Thời hạn hợp đồng')),
                ('loai_hop_dong', models.CharField(choices=[('Hợp đồng thử việc', 'Hợp đồng thử việc'), ('Hợp đồng có thời hạn', 'Hợp đồng có thời hạn')], default='Hợp đồng thử việc', max_length=100)),
                ('luong', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_ky', models.DateField()),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField()),
                ('trang_thai_hop_dong', models.CharField(choices=[('Đang hiệu lực', 'Đang hiệu lực'), ('Sắp hết hạn', 'Sắp hết hạn'), ('Hết hiệu lực', 'Hết hiệu lực')], max_length=50)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='DONGBHXH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField(null=True)),
                ('ngay_ket_thuc', models.DateField(null=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='BHXH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_BHXH', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Mã BHXH phải có đúng 10 chữ số', regex='^\\d{10}$')])),
                ('nhan_vien_dong', models.DecimalField(decimal_places=2, default=10.5, max_digits=5)),
                ('truong_dong', models.DecimalField(decimal_places=2, default=21.5, max_digits=5)),
                ('thoi_gian_bat_dau', models.DateField(null=True)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gio_vao', models.TimeField(blank=True, null=True, verbose_name='Giờ Vào')),
                ('gio_ra', models.TimeField(blank=True, null=True, verbose_name='Giờ Ra')),
                ('ngay', models.IntegerField(verbose_name='Ngày')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('trang_thai', models.IntegerField(choices=[(0, 'Đúng giờ'), (1, 'Nghỉ'), (2, 'Muộn')], verbose_name='Trạng Thái')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.nhanvien')),
            ],
            options={
                'ordering': ['nam', 'thang', 'ngay'],
                'unique_together': {('nhan_vien', 'ngay', 'thang', 'nam')},
            },
        ),
    ]
