# Generated by Django 4.2.8 on 2025-05-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nghiphep',
            name='nguoi_duyet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_duyet_don', to='HOME.nhanvien'),
        ),
    ]
