# Generated by Django 4.2.8 on 2025-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='dia_chi_tam_tru',
            field=models.TextField(null=True),
        ),
    ]
