# Generated by Django 4.2.8 on 2025-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_nhanvien_dia_chi_tam_tru'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhxh',
            name='thoi_gian_bat_dau',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dongbhxh',
            name='ngay_bat_dau',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dongbhxh',
            name='ngay_ket_thuc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kyluat',
            name='ly_do',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kyluat',
            name='ngay_bat_dau',
            field=models.DateField(null=True),
        ),
    ]
