# Generated by Django 4.2.8 on 2025-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_bhxh_thoi_gian_bat_dau_dongbhxh_ngay_bat_dau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nghiphep',
            name='ngay_bat_dau',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nghiphep',
            name='ngay_ket_thuc',
            field=models.DateField(null=True),
        ),
    ]
