# Generated by Django 4.2.8 on 2025-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_nghiphep_ngay_bat_dau_nghiphep_ngay_ket_thuc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyluat',
            name='ngay_bat_dau',
            field=models.DateField(),
        ),
    ]
