# Generated by Django 4.2.8 on 2025-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_alter_kyluat_ngay_bat_dau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsunghiphep',
            name='ngay_chinh_sua',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lichsunghiphep',
            name='ngay_tao_don',
            field=models.DateTimeField(null=True),
        ),
    ]
