# Generated by Django 4.2.8 on 2025-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_alter_lichsunghiphep_ngay_chinh_sua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='gioi_tinh',
            field=models.CharField(choices=[('2', 'Nam'), ('1', 'Nữ')], max_length=10),
        ),
    ]
