# Generated by Django 4.2.8 on 2025-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_alter_nhanvien_gioi_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='nghiphep',
            name='ngay_chinh_sua',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nghiphep',
            name='ngay_duyet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nghiphep',
            name='ngay_tao_don',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nghiphep',
            name='nguoi_duyet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LichSuNghiPhep',
        ),
    ]
