# Generated by Django 4.2.8 on 2025-04-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_nghiphep_ngay_chinh_sua_nghiphep_ngay_duyet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nghiphep',
            name='nguoi_duyet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_duyet_don', to='HOME.nhanvien'),
        ),
        migrations.AlterField(
            model_name='nghiphep',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_tao_don', to='HOME.nhanvien'),
        ),
    ]
